### PR TITLE
Whitaker xml

### PR DESCRIPTION
**Pull request by ibooksniffer**

### CODE REVIEW

**Comment by JacksonMeadeUNC** [comment]
Hey Sarah, could you let me know if I can use this to start the file, or if I should place it somewhere else? I'll turn this into edition.xml in a separate PR to start and request your permission for that, if that works with you.

**Review by JacksonMeadeUNC — APPROVED** [review]
I'm gonna go ahead and approve this so we can separate out the robots changes into a different check

**Comment by ibooksniffer** [comment]
Hi Jackson,
That should be fine to use. Do I still need to go in and approve anything
for this, or were you able to override?

**Comment by JacksonMeadeUNC** [comment]
I'll override; I'll add you on the PR in a minute when I push the changes necessary to pass robots.

**Pull request merged**
